# -*- coding: utf-8 -*-
"""Data_Cleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D35oyrvk47uAPR9HSxgo4A6rw1CDVdHY
"""

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
import os
import cv2
import numpy as np
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

data_dir = '/content/drive/MyDrive/CMPE257/stanford-car-dataset-by-classes-folder/car_data/car_data/train'
classes = os.listdir(data_dir)

X = []
y = []
for class_index, class_name in enumerate(classes):
    class_dir = os.path.join(data_dir, class_name)
    if os.path.isdir(class_dir):
        for image_name in os.listdir(class_dir):
            image_path = os.path.join(class_dir, image_name)
            image = cv2.imread(image_path)
            # image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
            image = cv2.resize(image, (100, 100))
            X.append(image.flatten())
            y.append(class_name.split()[0])

print('Finished loading images')

word_dict = {word: i for i, word in enumerate(set(y))}
y = [word_dict[word] for word in y]
            
X = np.array(X)
y = np.array(y)

X = X / 255.0
X, y = shuffle(X, y, random_state=42)